name: Build and Test Boids

on:
  push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Se fallisce un OS, continua a testare gli altri
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 1. Installazione Dipendenze (Ubuntu)
    
    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev libxcursor-dev libxinerama-dev libxrandr-dev libxi-dev libgl1-mesa-dev libomp-dev
        
        git clone --depth 1 --branch 5.0 https://github.com/raysan5/raylib.git
        cd raylib/src
        make PLATFORM=PLATFORM_DESKTOP -j$(nproc)
        sudo make install
    
    # 2. Installazione Dipendenze (macOS)
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install cmake raylib libomp

    # 3. Installazione Dipendenze (Windows)
    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: vcpkg install raylib:x64-windows

    # 4. Installazione di uv 
    - name: Setup uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    # 5. Configurazione CMake
    - name: Configure CMake (Linux)
      if: runner.os == 'Linux'
      run: cmake -B cmake-build-release -DCMAKE_BUILD_TYPE=Release

    - name: Configure CMake (macOS)
      if: runner.os == 'macOS'
      run: |
        cmake -B cmake-build-release -DCMAKE_BUILD_TYPE=Release \
          -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp -I$(brew --prefix libomp)/include" \
          -DOpenMP_C_LIB_NAMES="omp" \
          -DOpenMP_omp_LIBRARY="$(brew --prefix libomp)/lib/libomp.dylib"

    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      run: cmake -B cmake-build-release -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"

    # 6. Compilazione Multipiattaforma
    - name: Build
      run: cmake --build cmake-build-release --config Release --parallel 4

    # 7. Esecuzione Test
    - name: Run Demo Scripts
      run: cd scripts && uv run python run_demo.py
